name: homepage Actions Runner Controller
on:
  workflow_dispatch:

jobs:
  Explorer-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: homepage-arc
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
