services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    network_mode: "host"
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix://var/run/docker-host.sock
      - ENVIRONMENT=development
      - RUST_LOG=debug
    depends_on:
      - redis

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data: