apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - ../../base

images:
  - name: harbor.yuiop.org/homepage/homepage-backend
    newTag: latest  # GitHub Actions가 자동 업데이트

replicas:
  - name: homepage-backend
    count: 2

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: homepage-backend
      spec:
        template:
          spec:
            containers:
            - name: homepage-backend
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "1Gi"
                  cpu: "1000m"