apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage 

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml 
  - httproute.yaml
  # - configmap.yaml

labels:
  app: homepage-backend
  managed-by: kustomize 
